spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/delivery-hub
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

environment:
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

logging.level:
  org.hibernate.SQL: debug
